### PR TITLE
Add GNUGPLv3

### PR DESCRIPTION
**Pull request by GamerBene19**
This PR
 - changes name in `package.json` to `mensatt-frontend` (long overdue)
 - adds information about licenses of dependencies and scripts to manage them
 - sets GNUGPLv3 license

As we are changing the license with this PR we need explicit approval from all contributors.
@maanex, @herkulessi and @stormofice please comment that you consent to this change.

I - the third contributor - obviously do consent.

### CODE REVIEW

**Review by stormofice — APPROVED** [review]

**Review by stormofice — CHANGES_REQUESTED** [review]
As we make this repository public soon after merging this PR, we should adjust the readme's contributing section to reflect the change.

**Review by herkulessi — DISMISSED** [review]
Looks good, you have done more for mensatt than I did, so go ahead

**Comment by GamerBene19** [comment]
> As we make this repository public soon after merging this PR, we should adjust the readme's contributing section to reflect the change.

Good point - I've edited the readme - could you take a look again

**Review by stormofice — APPROVED** [review]

**Review by maanex — APPROVED** [review]

**Comment by GamerBene19** [comment]
Merging since all Contributors have approved this PR :+1:

**Pull request merged**
